### PR TITLE
set the redirect URL dynamically based on hostname

### PR DESCRIPTION
**Pull request by stadeltobi**
That way, authentication will also work for instances where you run
October on multiple subdomains. Comes in very handy when you also
use the keios/multisite plugin, which allows you to map themes
to hostnames dynamically

We currently use keios/multisite, since we're hosting multiple themes in one October instance, and we can then just point users to themeA.oursite.com or themeB.oursite.com, and they'll only see the content they need to worry about.

We also use this plugin, which always redirects the user to a fixed host that is stored in the database. 

With that change, the redirect IP is depending on the origin of the request.

### CODE REVIEW

**Comment by skydiver** [comment]
Sounds fine to me.

Not sure if must be an option like "autodetect redirect address" or just remove completely ...

**Comment by stadeltobi** [comment]
...which reminds me that I didn't think of saying a big "thanks" for this great plugin in my initial request. So: Thank you!

Anyway. Come to think of it, I can't think of a reason why you'd need to be able to configure a redirect URI in the plugin itself at all - the user signs in on the login page, which is something like foo.com, so that's where they'll be redirected to. Unless of course that for some reason, there's users out there who choose to host their login page on a different subdomain than the October backend itself. Which would be kinda weird, but you never know...

So I basically see two options here:
* add an extra configuration option like "redirect to static address" vs. "redirect dynamically", and have the code check for what the user has set in their plugin settings, and then do the right thing
* remove the "redirect URI" thing completely, and go with the dynamic behavior.

I'd offer to to whichever one you prefer - just let me know, I'll update the pull request.

Cheers
Tobi

**Comment by skydiver** [comment]
new version released. thanks for your help.

**Comment by stadeltobi** [comment]
awesome. Will try, but it looks like it should work. Thanks!

**Comment by stadeltobi** [comment]
We updated, and everything works like a charm. Thanks again for your efforts to provide this plugin, and for making the release happen so quickly. If everything in life were that easy :)

**Pull request merged**
